name: ChatControl
main: kangarko.chatcontrol.ChatControl
version: 5.0.0-DEV
author: kangarko
soft-depend: [Essentials, Vault, Multiverse-Core, ProtocolLib, Towny]
commands: 
  chatcontrol:
    aliases: [ccontrol, chatc, chc]
    description: Main ChatControl command. Type /chatcontrol list for commands.
permissions:
    chatcontrol.notify.whenmentioned:
        default: true
        description: Play sound to player when notified by another player and function is enabled.