name: ChatControl
main: chatcontrol.ChatControl
version: 4.5.6
author: kangarko
soft-depend: [Essentials, PermissionsEx, Multiverse-Core, ProtocolLib, Towny]
commands: 
  chatcontrol:
    aliases: [ccontrol, chatc, chc]
    description: Main ChatControl command. Type /chatcontrol list for commands.
permissions:
    chatcontrol.notify.whenmentioned:
        default: true
        description: Play sound to player when notified by another player and function is enabled.