name: ChatControl
main: chatcontrol.ChatControl
version: 4.4.8
author: kangarko
soft-depend: [PermissionsEx, Multiverse-Core, ProtocolLib]
commands: 
  chatcontrol:
    aliases: [ccontrol, chatc, chc]
    description: Main ChatControl command. Type /chatcontrol list for commands.