name: ChatControl
main: chatcontrol.ChatControl
version: 4.4.5
author: kangarko
soft-depend: [ProtocolLib]
commands: 
  chatcontrol:
    aliases: [ccontrol, chatc, chc]
    description: Main ChatControl command. Type /chatcontrol list for commands.